export enum WebsocketType {
  USER_RECEPCAO = 'USER_RECEPCAO',
  USER_ATENDIMENTO = 'USER_ATENDIMENTO',
  USER_PREPARO = 'USER_PREPARO',
  TICKET = 'TICKET',
  PAINEL = 'PAINEL',
  PRINTER = 'PRINTER',
  PRONTUARIO = 'PRONTUARIO',
  SCRAPER = 'SCRAPER',
  BIOMETRIA_AGENT = 'BIOMETRIA_AGENT',
  TELEATENDIMENTO = 'TELEATENDIMENTO',
  GED_BATCH = 'GED_BATCH',
  MURAL = 'MURAL',
}

export enum PreparationRequestTypes {
  CREATE = 'CREATE',

  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  FINISHED = 'FINISHED',
}
