export const AUDIT_ACTION_OPTIONS = [
  { label: "Recepção atualizada", value: "RECEPCAO_ATUALIZAR" },
  { label: "Exame atualizado", value: "EXAME_ATUALIZAR" },
  { label: "Exame reemitido", value: "EXAME_REEMITIR" },
  { label: "Resultado anexado", value: "ANEXAR_RESULTADO" },
  { label: "Anexo enviado", value: "UPLOAD_ANEXO" },
  { label: "Anexo removido", value: "REMOVER_ANEXO" },
  { label: "Atendimento excluído", value: "EXCLUIR_ATENDIMENTO" },
  { label: "Prontuário visualizado", value: "VISUALIZAR_PRONTUARIO" },
  { label: "Documento visualizado", value: "VISUALIZAR_DOCUMENTO_PROXY" },
  { label: "Documento visualizado (fallback)", value: "VISUALIZAR_DOCUMENTO_PROXY_FALLBACK" },
  { label: "Configuração alterada", value: "CONFIGURACAO_ALTERAR" },
  { label: "Biometria cadastrada", value: "BIOMETRIA_CADASTRO_SUCESSO" },
  { label: "Biometria aprovada", value: "BIOMETRIA_VALIDACAO_APROVADA" },
  { label: "Biometria reprovada", value: "BIOMETRIA_VALIDACAO_REPROVADA" },
  { label: "Ciência biométrica registrada", value: "BIOMETRIA_CIENCIA_REGISTRADA" },
  { label: "Termo biométrico gerado", value: "BIOMETRIA_TERMO_GERADO" },
  { label: "Consentimento aceito", value: "CONSENTIMENTO_ACEITO" },
  { label: "Consentimento rejeitado", value: "CONSENTIMENTO_REJEITADO" },
  { label: "Exame criado", value: "CRIAR_EXAME" },
  { label: "Exame editado", value: "EDITAR_EXAME" },
  { label: "Exame excluído", value: "EXCLUIR_EXAME" },
  { label: "Usuário atualizado", value: "USUARIO_ATUALIZADO" },
  { label: "Usuário excluído", value: "USUARIO_EXCLUIDO" },
  { label: "Usuário sincronizado", value: "USUARIO_SINCRONIZADO" },
  { label: "Unidade excluída", value: "EXCLUIR_UNIDADE" },
  { label: "Configuração de risco criada", value: "CRIAR_RISCO_CONFIG" },
  { label: "Configuração de risco editada", value: "EDITAR_RISCO_CONFIG" },
  { label: "Configuração de risco excluída", value: "EXCLUIR_RISCO_CONFIG" },
  { label: "Prestador criado", value: "CRIAR_PRESTADOR" },
  { label: "Prestador editado", value: "EDITAR_PRESTADOR" },
  { label: "Prestador excluído", value: "EXCLUIR_PRESTADOR" },
  { label: "Grupo criado", value: "CRIAR_GRUPO" },
  { label: "Grupo editado", value: "EDITAR_GRUPO" },
  { label: "Grupo excluído", value: "EXCLUIR_GRUPO" },
];
