export const ACAO_LABELS: Record<string, string> = {
  RECEPCAO_ATUALIZAR: "Recepção atualizada",
  EXAME_ATUALIZAR: "Exame atualizado",
  EXAME_REEMITIR: "Exame reemitido",
  ANEXAR_RESULTADO: "Resultado anexado",
  UPLOAD_ANEXO: "Anexo enviado",
  REMOVER_ANEXO: "Anexo removido",
  EXCLUIR_ATENDIMENTO: "Atendimento excluído",
  VISUALIZAR_PRONTUARIO: "Prontuário visualizado",
  CONFIGURACAO_ALTERAR: "Configuração alterada",
  BIOMETRIA_CADASTRO_SUCESSO: "Biometria cadastrada",
  BIOMETRIA_VALIDACAO_APROVADA: "Biometria aprovada",
  BIOMETRIA_VALIDACAO_REPROVADA: "Biometria reprovada",
  BIOMETRIA_CIENCIA_REGISTRADA: "Ciência biométrica registrada",
  BIOMETRIA_TERMO_GERADO: "Termo biométrico gerado",
  CONSENTIMENTO_ACEITO: "Consentimento aceito",
  CONSENTIMENTO_REJEITADO: "Consentimento rejeitado",
  CRIAR_EXAME: "Exame criado",
  EDITAR_EXAME: "Exame editado",
  EXCLUIR_EXAME: "Exame excluído",
  USUARIO_ATUALIZADO: "Usuário atualizado",
  USUARIO_EXCLUIDO: "Usuário excluído",
  USUARIO_SINCRONIZADO: "Usuário sincronizado",
  EXCLUIR_UNIDADE: "Unidade excluída",
  VISUALIZAR_DOCUMENTO_PROXY: "Documento visualizado",
  VISUALIZAR_DOCUMENTO_PROXY_FALLBACK: "Documento visualizado (fallback)",
  CRIAR_RISCO_CONFIG: "Configuração de risco criada",
  EDITAR_RISCO_CONFIG: "Configuração de risco editada",
  EXCLUIR_RISCO_CONFIG: "Configuração de risco excluída",
  CRIAR_PRESTADOR: "Prestador criado",
  EDITAR_PRESTADOR: "Prestador editado",
  EXCLUIR_PRESTADOR: "Prestador excluído",
  CRIAR_GRUPO: "Grupo criado",
  EDITAR_GRUPO: "Grupo editado",
  EXCLUIR_GRUPO: "Grupo excluído",
};

export function getAcaoLabel(acao: string): string {
  return ACAO_LABELS[acao] ?? acao;
}
